---

- name: Some packages
  apt:
    pkg: "{{ item }}"
    cache_valid_time: 3600
  with_items:
    - libpam-apparmor
    - auditd
    - borgbackup

- name: Borg user
  user:
    name: "{{ borg_user }}"
    comment: Borg user
    state: present
